name: Build (multiarch) + release

on:
  create:
    tags:
      - "*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'
        path: "builder"

    - uses: actions/checkout@v3
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        repository: 'aceberg/WatchYourLAN'
        ref: '${{ github.ref_name }}'
        path: "upstream"

    - uses: actions/checkout@v3
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      with:
        repository: 'aceberg/WatchYourLAN'
        ref: 'main'
        path: "upstream"

    - run: bash builder/build/ci/build_multiarch.sh ${{ github.ref_name }}

    - uses: softprops/action-gh-release@v1
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        body: 'https://github.com/aceberg/WatchYourLAN/releases/tag/${{ github.ref_name }}'
        files: |
          watchyourlan-*.tar.gz
          watchyourlan-*.zip
          watchyourlan-*.deb

    - uses: actions/upload-artifact@v3
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      with:
        name: watchyourlan-${{ github.ref_name }}
        path: |
          watchyourlan-*.tar.gz
          watchyourlan-*.zip
          watchyourlan-*.deb
